/**
 * On-device report/receipt exports. PDFs render from HTML via expo-print,
 * CSVs are written to the cache dir — everything goes out through the
 * Android share sheet. No server calls, no cloud storage consumed.
 */
import { File, Paths } from "expo-file-system";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

import type { BillDetail, ReportData } from "@/lib/data";
import { billTime, formatINR, longDate } from "@/lib/format";

/* ---------------- shared ---------------- */

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// PDFs stay light-themed for print friendliness regardless of app theme.
const PDF_STYLE = `
  <style>
    * { box-sizing: border-box; }
    body { font-family: Helvetica, Arial, sans-serif; color: #0f172a; margin: 24px; }
    h1 { font-size: 20px; margin: 0; }
    h2 { font-size: 13px; margin: 24px 0 8px; text-transform: uppercase; letter-spacing: 0.08em; color: #475569; }
    .muted { color: #64748b; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { text-align: left; color: #475569; font-weight: 600; padding: 6px 8px; border-bottom: 2px solid #e2e8f0; }
    td { padding: 6px 8px; border-bottom: 1px solid #eef2f7; }
    td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
    .grid { display: flex; gap: 12px; margin-top: 12px; }
    .stat { flex: 1; border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 12px; }
    .stat .v { font-size: 18px; font-weight: 700; margin-top: 2px; }
    .footer { margin-top: 28px; font-size: 11px; color: #94a3b8; text-align: center; }
  </style>`;

async function sharePdf(html: string, dialogTitle: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, {
    mimeType: "application/pdf",
    dialogTitle,
    UTI: "com.adobe.pdf",
  });
}

/* ---------------- sales report ---------------- */

export async function shareReportPdf(
  report: ReportData,
  restaurantName: string
): Promise<void> {
  const range =
    report.fromDay === report.toDay
      ? longDate(report.fromDay)
      : `${longDate(report.fromDay)} — ${longDate(report.toDay)}`;

  const splitRows = (
    [
      ["Cash", report.split.cash],
      ["UPI", report.split.upi],
      ["Card", report.split.card],
      ["Credit", report.split.credit],
    ] as const
  )
    .map(
      ([label, v]) =>
        `<tr><td>${label}</td><td class="num">${formatINR(v)}</td><td class="num">${
          report.total > 0 ? Math.round((v / report.total) * 100) : 0
        }%</td></tr>`
    )
    .join("");

  const itemRows = report.items
    .map(
      (it, i) =>
        `<tr><td>${i + 1}</td><td>${esc(it.name)}</td><td class="num">${it.quantity}</td><td class="num">${formatINR(it.amount)}</td></tr>`
    )
    .join("");

  const html = `<!doctype html><html><head><meta charset="utf-8">${PDF_STYLE}</head><body>
    <h1>${esc(restaurantName)}</h1>
    <div class="muted">Sales report · ${range}</div>
    <div class="grid">
      <div class="stat"><div class="muted">Total sales</div><div class="v">${formatINR(report.total)}</div></div>
      <div class="stat"><div class="muted">Bills</div><div class="v">${report.billCount}</div></div>
      <div class="stat"><div class="muted">Avg bill</div><div class="v">${formatINR(Math.round(report.avg))}</div></div>
    </div>
    <div class="grid">
      <div class="stat"><div class="muted">Subtotal</div><div class="v">${formatINR(report.subtotal)}</div></div>
      <div class="stat"><div class="muted">GST</div><div class="v">${formatINR(report.gst)}</div></div>
      <div class="stat"><div class="muted">Expenses</div><div class="v">${formatINR(report.expenseTotal)}</div></div>
    </div>
    <h2>Payment modes</h2>
    <table><tr><th>Mode</th><th class="num">Amount</th><th class="num">Share</th></tr>${splitRows}</table>
    <h2>Item-wise sales</h2>
    <table><tr><th>#</th><th>Item</th><th class="num">Qty</th><th class="num">Amount</th></tr>${
      itemRows || `<tr><td colspan="4" class="muted">No items in this range</td></tr>`
    }</table>
    <div class="footer">Generated by Magic Bill · magicbill.in</div>
  </body></html>`;

  await sharePdf(html, "Share sales report");
}

export async function shareReportCsv(
  report: ReportData,
  restaurantName: string
): Promise<void> {
  const q = (s: string) => `"${s.replace(/"/g, '""')}"`;
  const lines: string[] = [];
  lines.push(`${q(restaurantName)},Sales report,${report.fromDay} to ${report.toDay}`);
  lines.push("");
  lines.push("Summary");
  lines.push(`Total,${report.total.toFixed(2)}`);
  lines.push(`Subtotal,${report.subtotal.toFixed(2)}`);
  lines.push(`GST,${report.gst.toFixed(2)}`);
  lines.push(`Bills,${report.billCount}`);
  lines.push(`Average bill,${report.avg.toFixed(2)}`);
  lines.push(`Expenses,${report.expenseTotal.toFixed(2)}`);
  lines.push("");
  lines.push("Payment mode,Amount");
  lines.push(`Cash,${report.split.cash.toFixed(2)}`);
  lines.push(`UPI,${report.split.upi.toFixed(2)}`);
  lines.push(`Card,${report.split.card.toFixed(2)}`);
  lines.push(`Credit,${report.split.credit.toFixed(2)}`);
  lines.push("");
  lines.push("Item,Quantity,Amount");
  for (const it of report.items) {
    lines.push(`${q(it.name)},${it.quantity},${it.amount.toFixed(2)}`);
  }
  lines.push("");
  lines.push("Bill No,Time,Type,Table,Payment,Subtotal,GST,Total");
  for (const b of report.bills) {
    lines.push(
      [
        q(b.bill_number ?? ""),
        q(billTime(b.billed_at)),
        q(b.order_type ?? ""),
        q(b.table_number ?? ""),
        q(b.payment_mode ?? ""),
        (b.subtotal ?? 0).toFixed(2),
        (b.gst ?? 0).toFixed(2),
        (b.total ?? 0).toFixed(2),
      ].join(",")
    );
  }

  const file = new File(
    Paths.cache,
    `magicbill-report-${report.fromDay}-${report.toDay}.csv`
  );
  file.write(lines.join("\n"));
  await Sharing.shareAsync(file.uri, {
    mimeType: "text/csv",
    dialogTitle: "Share sales report (CSV)",
  });
}

/* ---------------- receipt ---------------- */

export async function shareReceiptPdf(
  bill: BillDetail,
  restaurantName: string
): Promise<void> {
  const itemRows = (bill.items ?? [])
    .map(
      (it) =>
        `<tr><td>${esc(it.name)}</td><td class="num">${it.quantity} × ${formatINR(Number(it.price) || 0)}</td><td class="num">${formatINR((Number(it.price) || 0) * (Number(it.quantity) || 0))}</td></tr>`
    )
    .join("");

  const html = `<!doctype html><html><head><meta charset="utf-8"><style>
    body { font-family: 'Courier New', monospace; color: #111; width: 300px; margin: 16px auto; font-size: 12px; }
    .c { text-align: center; }
    h1 { font-size: 16px; margin: 0; text-align: center; }
    hr { border: none; border-top: 1px dashed #999; margin: 8px 0; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    td { padding: 2px 0; vertical-align: top; }
    td.num { text-align: right; white-space: nowrap; }
    .tot { font-weight: 700; font-size: 14px; }
  </style></head><body>
    <h1>${esc(restaurantName)}</h1>
    <div class="c">${bill.bill_number ? `Bill #${esc(bill.bill_number)}` : ""}${
      bill.token_number != null ? ` · Token ${bill.token_number}` : ""
    }</div>
    <div class="c">${billTime(bill.billed_at)}</div>
    ${bill.order_type ? `<div class="c">${esc(bill.order_type)}${bill.table_number ? ` · Table ${esc(bill.table_number)}` : ""}</div>` : ""}
    ${bill.customer_name ? `<div class="c">Customer: ${esc(bill.customer_name)}</div>` : ""}
    <hr/>
    <table>${itemRows}</table>
    <hr/>
    <table>
      <tr><td>Subtotal</td><td class="num">${formatINR(bill.subtotal ?? 0)}</td></tr>
      <tr><td>GST</td><td class="num">${formatINR(bill.gst ?? 0)}</td></tr>
      <tr class="tot"><td>TOTAL</td><td class="num tot">${formatINR(bill.total ?? 0)}</td></tr>
      ${bill.payment_mode ? `<tr><td>Paid by</td><td class="num">${esc(bill.payment_mode)}</td></tr>` : ""}
    </table>
    <hr/>
    <div class="c">Thank you! Visit again.</div>
    <div class="c">Powered by Magic Bill</div>
  </body></html>`;

  await sharePdf(html, "Share receipt");
}
